import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "@/providers/lenis-provider";
import { FloatingWhatsAppButton } from "@/components/ui/floating-whatsapp";
import { Navbar } from "@/components/shared/navbar";
import { MobileTabBar } from "@/components/shared/mobile-tab-bar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} ${playfair.variable} antialiased`}
      >
        <Navbar />
        <MobileTabBar />
        <LenisProvider>
          <main className="pb-20 md:pb-0 min-h-screen">
            {children}
          </main>
          <FloatingWhatsAppButton />
        </LenisProvider>
      </body>
    </html>
  );
}
